FROM openjdk:17.0.2-jdk-slim-buster
MAINTAINER uPagge <me@upagge.ru>
RUN apt upgrade && addgroup gitlabbot --disabled-password && \
    adduser gitlabbot --ingroup gitlabbot && \
    mkdir -p /bot && \
    chown -R gitlabbot:gitlabbot /bot
WORKDIR /bot
USER gitlabbot:gitlabbot
COPY target/gitlab-notification.jar app.jar
ENV TELEGRAM_PERSON_ID=TELEGRAM_PERSON_ID DATASOURCE_URL=DATASOURCE_URL \
    DATASOURCE_PASSWORD=DATASOURCE_PASSWORD DATASOURCE_USERNAME=DATASOURCE_USERNAME \
    GITLAB_PERSONAL_TOKEN=GITLAB_PERSONAL_TOKEN TELEGRAM_BOT_TOKEN=TELEGRAM_BOT_TOKEN \
    TELEGRAM_BOT_USERNAME=TELEGRAM_BOT_USERNAME GITLAB_URL=GITLAB_URL GITLAB_REPLACE_URL=GITLAB_REPLACE_URL
ENTRYPOINT java -DTELEGRAM_BOT_USERNAME=${TELEGRAM_BOT_USERNAME} \
                    -DTELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN \
                    -DTELEGRAM_PERSON_ID=$TELEGRAM_PERSON_ID \
                    -DDATASOURCE_URL=$DATASOURCE_URL \
                    -DDATASOURCE_PASSWORD=$DATASOURCE_PASSWORD \
                    -DDATASOURCE_USERNAME=$DATASOURCE_USERNAME \
                    -DGITLAB_PERSONAL_TOKEN=$GITLAB_PERSONAL_TOKEN \
                    -DGITLAB_URL=$GITLAB_URL \
                    -DGITLAB_REPLACE_URL=$GITLAB_REPLACE_URL \
                    -jar app.jar