---
kind: pipeline
type: docker
name: develop build

trigger:
  branch:
    - develop

services:
  - name: docker
    image: docker:20.10.22-dind-alpine3.17
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: m2
    host:
      path: /drone/volume/m2
  - name: dockersock
    temp: {}

steps:
  - name: create jar
    image: maven:3.8.6-eclipse-temurin-17
    volumes:
      - name: m2
        path: /root/.m2/repository
    commands:
      - mvn -U clean package

  - name: docker publish develop
    image: upagge/docker-buildx:latest
    environment:
      DOCKER_REGISTRY_TOKEN:
        from_secret: DOCKER_REGISTRY_TOKEN
      DOCKER_IMAGE_NAME:
        from_secret: DOCKER_IMAGE_NAME
      DOCKER_REGISTRY_USER:
        from_secret: DOCKER_REGISTRY_USER
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - echo "$DOCKER_REGISTRY_TOKEN" | docker login docker.io --username $DOCKER_REGISTRY_USER --password-stdin
      - docker buildx create --use
      - docker buildx build -f Dockerfile-develop --push --platform linux/amd64,linux/arm64/v8 -t "$DOCKER_IMAGE_NAME:develop" .

---

kind: pipeline
type: docker
name: release build

trigger:
  ref:
    - refs/tags/v.*.*.*

services:
  - name: docker
    image: docker:20.10.22-dind-alpine3.17
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: m2
    host:
      path: /drone/volume/m2
  - name: dockersock
    temp: {}

steps:
  - name: create jar
    image: maven:3.8.6-eclipse-temurin-17
    volumes:
      - name: m2
        path: /root/.m2/repository
    commands:
      - mvn -U clean package

  - name: docker publish release
    image: upagge/docker-buildx:latest
    environment:
      DOCKER_REGISTRY_TOKEN:
        from_secret: DOCKER_REGISTRY_TOKEN
      DOCKER_IMAGE_NAME:
        from_secret: DOCKER_IMAGE_NAME
      DOCKER_REGISTRY_USER:
        from_secret: DOCKER_REGISTRY_USER
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - echo "$DOCKER_REGISTRY_TOKEN" | docker login docker.io --username $DOCKER_REGISTRY_USER --password-stdin
      - docker buildx create --use
      - docker buildx build --push --platform linux/amd64,linux/arm64/v8 -t "$DOCKER_IMAGE_NAME:latest" -t "$DOCKER_IMAGE_NAME:$DRONE_TAG" .

---
kind: pipeline
type: docker
name: create-docs-site

trigger:
  branch:
    - docs

clone:
  depth: 1

steps:
  - name: build site
    image: git.struchkov.dev/upagge/mkdocs-material-insiders:latest
    volumes:
      - name: mkdocs_cache
        path: ${DRONE_WORKSPACE}/documentation/.cache
    commands:
      - cd documentation
      - mike deploy --prefix gitlab-notification --branch docs-deploy --push --update-aliases develop

image_pull_secrets:
  - DOCKER_AUTH

volumes:
  - name: mkdocs_cache
    host:
      path: /drone/volume/mkdocs_cache/gitlab_notification

---
kind: signature
hmac: fcd23a173d0a823ff39f9efe454d936476d49f03840034af7dd2c671571004d4

...
