kind: pipeline
type: docker
name: gitlab-notify

steps:
  - name: package
    image: maven:3.8.6-eclipse-temurin-17
    commands:
      - mvn -U clean package
    volumes:
      - name: m2
        path: /root/.m2

trigger:
  branch:
    - master

volumes:
  - name: m2
    host:
      path: $MAVEN_REPO