site_name: GitLab Notification
site_url: https://docs.struchkov.dev/gitlab-notification/ru/

repo_url: https://github.com/uPagge/gitlab-notification
repo_name: uPagge/gitlab-notification
edit_uri: edit/develop/documentation/ru/docs

nav:
  - О проекте: index.md
  - Конфиденциальность: privacy.md
  - Возможности:
    - Уведомления: features/notify.md
    - Быстрые действия: features/interaction-gitlab.md
  - Быстрый старт:
      - getting-started/create-gitlab-token.md
      - getting-started/creating-telegram-bot.md
      - getting-started/configuration.md
      - getting-started/first-start.md
  - Архитектура:
      - Общее: architecture/concept.md
#  - Блог:
#      - blog/index.md
  - "Поддержать разработку":
      - support-development/index.md
  - ChangeLog:
      - changelog/index.md

theme:
  name: material
  custom_dir: overrides
  language: ru
#  favicon: assets/favicon.ico
  icon:
    logo: simple/gitlab
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme)"
      primary: deep orange
      accent: orange
      scheme: default
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      primary: deep orange
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.sections
    - navigation.tracking
    - navigation.footer
    - navigation.prune
    - search
    - search.suggest
    - search.highlight
    - content.action.edit
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - toc.follow
    - toc.integrate
plugins:
  - social
  - typeset
#  - blog:
#      blog_toc: true
#      post_date_format: short
#      post_url_format: "{slug}"
#      archive_toc: true
#      categories: false
#      authors: false
#  - optimize:
#      optimize_jpg_quality: 90
  - tags
  - search:
      lang: ru

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - abbr
  - md_in_html
  - footnotes
  - toc:
      toc_depth: 3
      title: Содержание
      permalink: ⚓︎

extra_css:
  - stylesheets/extra.css
extra:
  generator: false
  analytics:
    provider: custom
    property: foobar
  version:
    provider: mike
#  social:
#    - icon: fontawesome/brands/telegram
#      link: https://t.me/dev_java_blog
#  alternate:
#    - name: Русский
#      link: /gitlab-notification/ru/
#      lang: ru
#    - name: English
#      link: /gitlab-notification/en/
#      lang: en