site_name: GitLab Notification
site_url: https://docs.struchkov.dev/gitlab-notification/

repo_url: https://github.com/uPagge/gitlab-notification
repo_name: uPagge/gitlab-notification
#edit_uri: edit/master/documentation/docs

nav:
  - О проекте: index.md
  - Возможности: getting-started/features.md
  - Быстрый старт:
      - Запуск: getting-started/configuration.md
  - Архитектура:
      - Концепт: architecture/concept.md
  - "Поддержать разработку":
      - support-development/index.md
  - ChangeLog:
      - changelog/index.md

theme:
  name: material
  custom_dir: overrides
  language: ru
#  favicon: assets/favicon.ico
  icon:
    logo: simple/gitlab
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: deep orange
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.sections
    - navigation.tracking
    - navigation.footer
    - navigation.path
    - navigation.prune
    - search
    - search.suggest
    - search.highlight
    - content.action.edit
    - content.code.copy
    - toc.follow
    - toc.integrate
plugins:
  - social
#  - meta
  - tags
  - search:
      lang: ru
#  - optimize:
#      concurrency: 1
#      optimize_jpg_quality: 90

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
      title: Содержание

extra:
  generator: false
  analytics:
    provider: custom
    property: foobar
  version:
    provider: mike
  alternate:
    - name: Русский
      link: /gitlab-notification/ru/
      lang: ru
    - name: English
      link: /gitlab-notification/en/
      lang: en