server:
  port: 8018
spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    driver-class-name: org.postgresql.Driver
    password: ${DATASOURCE_PASSWORD}
  liquibase:
    change-log: classpath:liquibase/change-log.xml
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
telegram-config:
  bot-username: ${TELEGRAM_BOT_USERNAME}
  bot-token: ${TELEGRAM_BOT_TOKEN}
gitlab-bot:
  version: 2.15.3
  scheduler:
    comment:
      settings:
        no-comment-count: 20
        comment-count: 100
  person:
    telegram-id: ${TELEGRAM_PERSON_ID}
    token: ${GITLAB_PERSONAL_TOKEN}
  gitlab:
    url-project: ${GITLAB_URL}/api/v4/projects?page={0}&per_page=100
    url-pull-request-open: ${GITLAB_URL}/api/v4/projects/{0}/merge_requests?state=opened&page={1}&per_page=100
    url-pull-request-close: ${GITLAB_URL}
    url-pull-request-comment: ${GITLAB_URL}/api/v4/projects/{0}/merge_requests/{1}/notes
    url-pull-request: ${GITLAB_URL}/api/v4/projects/{0}/merge_requests/{1}?page={2}&per_page=100
    user-url: ${GITLAB_URL}/api/v4/user
    users-url: ${GITLAB_URL}/api/v4/users
  teamcity:
    token: ${TEAMCITY_ADMIN_TOKEN}
    project-url: ${TEAMCITY_URL}/app/rest/projects
    build-url: ${TEAMCITY_URL}/app/rest/builds/?locator=project:(id:{0}),branch:(default:any)