spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    driver-class-name: org.postgresql.Driver
    password: ${DATASOURCE_PASSWORD}
  liquibase:
    change-log: classpath:liquibase/change-log.xml
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
logging:
  config: classpath:logback-dev.xml
bitbucketbot:
  scheduler:
    person: 0 */1 * * * *
    comment:
      settings:
        no-comment-count: 20
        comment-count: 100
  init:
    start-comment-id: 8301
    use: false
  rating:
    enable: true
  bitbucket:
    token: ${BITBUCKET_ADMIN_TOKEN}
    url-pull-request-open: ${BITBUCKET_URL}/rest/api/1.0/dashboard/pull-requests?limit=150&state=OPEN
    url-pull-request-close: ${BITBUCKET_URL}/rest/api/1.0/dashboard/pull-requests?limit=150&closedSince=86400
    url-pull-request-comment: ${BITBUCKET_URL}/rest/api/1.0/projects/{projectKey}/repos/{repositorySlug}/pull-requests/{pullRequestId}/comments/{commentId}
    url-pull-request: ${BITBUCKET_URL}/projects/{projectKey}/repos/{repositorySlug}/pull-requests/{pullRequestId}/overview
    url-users: ${BITBUCKET_URL}/rest/api/1.0/admin/users
  teamcity:
    token: ${TEAMCITY_ADMIN_TOKEN}
    project-url: ${TEAMCITY_URL}/app/rest/projects
    build-url: ${TEAMCITY_URL}/app/rest/builds/?locator=project:(id:{0}),branch:(default:any)