spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    driver-class-name: org.postgresql.Driver
    password: ${DATASOURCE_PASSWORD}
  liquibase:
    change-log: classpath:liquibase/changelog.xml
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
telegram-config:
  bot-username: ${TELEGRAM_BOT_USERNAME}
  bot-token: ${TELEGRAM_BOT_TOKEN}
  proxy-config:
    enable: ${PROXY_ENABLE:false}
    host: ${PROXY_HOST:host}
    port: ${PROXY_PORT:8080}
    type: ${PROXY_TYPE:SOCKS5}
    user: ${PROXY_USERNAME:}
    password: ${PROXY_PASSWORD:}

gitlab-bot:
  version: 0.0.7 Beta
  person:
    telegram-id: ${TELEGRAM_PERSON_ID}
    token: ${GITLAB_PERSONAL_TOKEN}
  gitlab:
    base-url: ${GITLAB_URL}
    replaceUrl: ${GITLAB_REPLACE_URL}
    url-project: ${GITLAB_URL}/api/v4/projects?page={0, number, integer}&per_page=100
    url-pull-request-open: "${GITLAB_URL}/api/v4/projects/{0,number,#}/merge_requests?state=opened&page={1, number, integer}&per_page=100"
    url-pull-request-close: "${GITLAB_URL}/api/v4/projects/{0,number,#}/merge_requests?state=closed&page={1, number, integer}&per_page=100"
    url-pull-request-comment: "${GITLAB_URL}/api/v4/projects/{0,number,#}/merge_requests/{1,number,#}/notes?&page={2,number,#}&per_page=100"
    url-pull-request: "${GITLAB_URL}/api/v4/projects/{0,number,#}/merge_requests/{1,number,#}"
    url-merge-request-add: "${GITLAB_URL}/api/v4/projects/"
    user-url: ${GITLAB_URL}/api/v4/user
    users-url: ${GITLAB_URL}/api/v4/users
    url-note: "{0}#note_{1,number,#}"
    url-note-api: "${GITLAB_URL}/api/v4/projects/{0,number,#}/merge_requests/{1,number,#}/notes/{2,number,#}"
    url-pipelines: "${GITLAB_URL}/api/v4/projects/{0,number,#}/pipelines?&page={1,number,#}&per_page=100"
    url-pipeline: "${GITLAB_URL}/api/v4/projects/{0,number,#}/pipelines/{1,number,#}"
    url-commit: "${GITLAB_URL}/api/v4/projects/{0,number,#}/merge_requests/{1,number,#}/commits?&page=1&per_page=1"
    url-new-note: "${GITLAB_URL}/api/v4/projects/{0,number,#}/merge_requests/{1,number,#}/discussions/{2}/notes?body={3}"
    url-discussion: "${GITLAB_URL}/api/v4/projects/{0,number,#}/merge_requests/{1,number,#}/discussions?&page={2,number,#}&per_page=100"
    url-one-discussion: "${GITLAB_URL}/api/v4/projects/{0,number,#}/merge_requests/{1,number,#}/discussions/{2}"