spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    driver-class-name: org.postgresql.Driver
    password: ${DATASOURCE_PASSWORD}
  liquibase:
    change-log: classpath:liquibase/changelog.xml
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
#  без данной настройк ипостоянно выбрасывается исключение:
# org.springframework.dao.InvalidDataAccessApiUsageException: Multiple representations of the
# same entity [dev.struchkov.bot.gitlab.context.domain.entity.Person#13445232] are being merged.
# Detached: [dev.struchkov.bot.gitlab.context.domain.entity.Person@cd28ab];
# Detached: [dev.struchkov.bot.gitlab.context.domain.entity.Person@cd28ab]
        event:
          merge.entity_copy_observer: allow

logging:
  level:
    "dev.struchkov": ${LOG_LEVEL:info}

telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME}
    token: ${TELEGRAM_BOT_TOKEN}
    autoresponder:
      threads: ${AUTORESPONDER_THREADS:8}
  proxy:
        event:
          merge.entity_copy_observer: allow
telegram-config:
  bot-username: ${TELEGRAM_BOT_USERNAME}
  bot-token: ${TELEGRAM_BOT_TOKEN}
  proxy-config:
    enable: ${PROXY_ENABLE:false}
    host: ${PROXY_HOST:}
    port: ${PROXY_PORT:}
    type: ${PROXY_TYPE:SOCKS5}
    user: ${PROXY_USERNAME:}
    password: ${PROXY_PASSWORD:}

gitlab-bot:
  version: 1.0.0
  cron:
    scan:
      general: "0 */1 * * * *"
      new-project: "0 0 */1 * * *"
      new-merge-request: "0 */15 * * * *"
  person:
    telegram-id: ${TELEGRAM_PERSON_ID}
    token: ${GITLAB_PERSONAL_TOKEN}
  gitlab:
    base-url: ${GITLAB_URL}
    replaceUrl: ${GITLAB_REPLACE_URL}
    users-url: "${GITLAB_URL}/api/v4/users"
    user-url: "${GITLAB_URL}/api/v4/user"
    projects-url: "${GITLAB_URL}/api/v4/projects?page={0, number, integer}&per_page=100"
    open-merge-requests-url: "${GITLAB_URL}/api/v4/projects/{0,number,#}/merge_requests?state=opened&page={1, number, integer}&per_page={2, number, integer}"
    close-merge-requests-url: "${GITLAB_URL}/api/v4/projects/{0,number,#}/merge_requests?state=closed&page={1, number, integer}&per_page=100"
    comments-of-merge-request-url: "${GITLAB_URL}/api/v4/projects/{0,number,#}/merge_requests/{1,number,#}/notes?&page={2,number,#}&per_page=100"
    merge-request-url: "${GITLAB_URL}/api/v4/projects/{0,number,#}/merge_requests/{1,number,#}"
    project-add-url: "${GITLAB_URL}/api/v4/projects/"
    note-url: "{0}#note_{1,number,#}"
    notes-of-merge-request-url: "${GITLAB_URL}/api/v4/projects/{0,number,#}/merge_requests/{1,number,#}/notes/{2,number,#}"
    pipelines-url: "${GITLAB_URL}/api/v4/projects/{0,number,#}/pipelines?&page={1,number,#}&per_page={2,number,#}"
    pipeline-url: "${GITLAB_URL}/api/v4/projects/{0,number,#}/pipelines/{1,number,#}"
    last-commit-of-merge-request-url: "${GITLAB_URL}/api/v4/projects/{0,number,#}/merge_requests/{1,number,#}/commits?&page=1&per_page=1"
    new-note-url: "${GITLAB_URL}/api/v4/projects/{0,number,#}/merge_requests/{1,number,#}/discussions/{2}/notes?body={3}"
    discussions-url: "${GITLAB_URL}/api/v4/projects/{0,number,#}/merge_requests/{1,number,#}/discussions?&page={2,number,#}&per_page={3,number,#}"
    discussion-url: "${GITLAB_URL}/api/v4/projects/{0,number,#}/merge_requests/{1,number,#}/discussions/{2}"
    issue-url: "${GITLAB_URL}/api/v4/projects/{0,number,#}/issues/{1,number,#}"
    open-issue-url: "${GITLAB_URL}/api/v4/projects/{0,number,#}/issues?state=opened&page={1, number, integer}&per_page={2, number, integer}"

---
spring:
  config:
    activate:
      on-profile: local

gitlab-bot:
  cron:
    scan:
      general: "0 */1 * * * *"
      new-project: "0 */1 * * * *"
      new-merge-request: "0 */1 * * * *"